package space

import (
	"context"
	"regexp"

	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
)

func (r *spaceResource) Schema(ctx context.Context, req resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema.Description = "Creates a Kibana space. See, https://www.elastic.co/guide/en/kibana/master/spaces-api-post.html"
	resp.Schema.Attributes = map[string]schema.Attribute{
		"id": schema.StringAttribute{
			Description: "Internal identifier of the resource.",
			Computed:    true,
		},
		"space_id": schema.StringAttribute{
			Description: "The space ID that is part of the Kibana URL when inside the space.",
			Required:    true,
			PlanModifiers: []planmodifier.String{
				stringplanmodifier.RequiresReplace(),
			},
		},
		"name": schema.StringAttribute{
			Description: "The display name for the space.",
			Required:    true,
		},
		"description": schema.StringAttribute{
			Description: "The description for the space.",
			Optional:    true,
		},
		"disabled_features": schema.SetAttribute{
			Description: "The list of disabled features for the space. To get a list of available feature IDs, use the Features API (https://www.elastic.co/guide/en/kibana/master/features-api-get.html).",
			Optional:    true,
			ElementType: types.StringType,
		},
		"initials": schema.StringAttribute{
			Description: "The initials shown in the space avatar. By default, the initials are automatically generated from the space name. Initials must be 1 or 2 characters.",
			Computed:    true, // If not provided, a value is autogenerated
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.LengthBetween(1, 2),
			},
		},
		"color": schema.StringAttribute{
			Description: "The hexadecimal color code used in the space avatar. By default, the color is automatically generated from the space name.",
			Computed:    true, // If not provided, a value is autogenerated
			Optional:    true,
		},
		"image_url": schema.StringAttribute{
			Description: "The data-URL encoded image to display in the space avatar.",
			Computed:    true,
			Optional:    true,
			Validators: []validator.String{
				stringvalidator.RegexMatches(regexp.MustCompile("^data:image/"), "must be a valid data-URL encoded image"),
			},
		},
	}
}
